// src/component/Sheet.tsx
import { Sheet } from '@daml.js/daml-project';
import { useEffect } from 'react';
import assert from '../helpers/assert';
import { key } from '../helpers/sheet';
import { useStore } from '../helpers/store';

type StatProps = {
  name: string;
  value: unknown;
};

const Stat = ({ name, value }: StatProps) => (
  <li className="flex w-1/2  items-center mt-4 text-gray-700">
    <h3 className="px-2 text-sm">
      <>
        <span className="text-base font-semibold">{name}: </span>
        {value}
      </>
    </h3>
  </li>
);

export default () => {
  const { sheet } = useStore();

  if (!sheet) return <>Loading...</>;

  const {
    name,
    hp,
    weapon: { ad, name: wname },
  } = sheet;

  return (
    <>
      <article className="w-full mx-auto max-w-lg overflow-hidden bg-white rounded-lg shadow-lg">
        <div className="flex items-center px-6 py-3 bg-gray-900">
          <h2 className="text-lg font-bold text-white">{name}</h2>
        </div>

        <div className="px-6 py-4 pb-6">
          <ul className="flex flex-col">
            <Stat name="HP" value={hp} />

            <Stat name="Weapon" value={wname} />

            <Stat name="AD" value={ad} />
          </ul>
        </div>
      </article>
    </>
  );
};

// src/Sheet.svelte
<script lang="ts">
  import Stat from './Stat.svelte';

  export let name = '';
  export let hp = '';
  export let weapon = '';
  export let stance = '';
</script>

<article
  class="w-full mx-auto max-w-lg overflow-hidden bg-white rounded-lg shadow-lg"
>
  <div class="flex items-center px-6 py-3 bg-gray-900">
    <h2 class="text-lg text-white font-semibold">
      {name}
    </h2>
  </div>

  <div class="px-6 py-3.5 pb-6">
    <ul class="flex flex-col justify-center">
      <Stat>
        <svg
          slot="icon"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="currentColor"
          class="w-6 h-6"
        >
          <path
            d="M11.645 20.91l-.007-.003-.022-.012a15.247 15.247 0 01-.383-.218 25.18 25.18 0 01-4.244-3.17C4.688 15.36 2.25 12.174 2.25 8.25 2.25 5.322 4.714 3 7.688 3A5.5 5.5 0 0112 5.052 5.5 5.5 0 0116.313 3c2.973 0 5.437 2.322 5.437 5.25 0 3.925-2.438 7.111-4.739 9.256a25.175 25.175 0 01-4.244 3.17 15.247 15.247 0 01-.383.219l-.022.012-.007.004-.003.001a.752.752 0 01-.704 0l-.003-.001z"
          />
        </svg>

        <span slot="attr">HP</span>

        <span slot="value">{`${hp}`}</span>
      </Stat>

      <Stat>
        <svg
          slot="icon"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="currentColor"
          class="w-6 h-6"
        >
          <path
            d="M11.645 20.91l-.007-.003-.022-.012a15.247 15.247 0 01-.383-.218 25.18 25.18 0 01-4.244-3.17C4.688 15.36 2.25 12.174 2.25 8.25 2.25 5.322 4.714 3 7.688 3A5.5 5.5 0 0112 5.052 5.5 5.5 0 0116.313 3c2.973 0 5.437 2.322 5.437 5.25 0 3.925-2.438 7.111-4.739 9.256a25.175 25.175 0 01-4.244 3.17 15.247 15.247 0 01-.383.219l-.022.012-.007.004-.003.001a.752.752 0 01-.704 0l-.003-.001z"
          />
        </svg>

        <span slot="attr">HP</span>

        <span slot="value">{`${hp}`}</span>
      </Stat>

      <Stat>
        <svg
          slot="icon"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="currentColor"
          class="w-6 h-6"
        >
          <path
            d="M11.645 20.91l-.007-.003-.022-.012a15.247 15.247 0 01-.383-.218 25.18 25.18 0 01-4.244-3.17C4.688 15.36 2.25 12.174 2.25 8.25 2.25 5.322 4.714 3 7.688 3A5.5 5.5 0 0112 5.052 5.5 5.5 0 0116.313 3c2.973 0 5.437 2.322 5.437 5.25 0 3.925-2.438 7.111-4.739 9.256a25.175 25.175 0 01-4.244 3.17 15.247 15.247 0 01-.383.219l-.022.012-.007.004-.003.001a.752.752 0 01-.704 0l-.003-.001z"
          />
        </svg>

        <span slot="attr">HP</span>

        <span slot="value">{`${hp}`}</span>
      </Stat>
    </ul>
  </div>
</article>
